[tool.poetry]
name = "pythonprojecte-commerce"
version = "0.1.0"
description = ""
authors = ["sergrih1980-sys <sergrih1980@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
